<?php

declare(strict_types=1);

namespace ElegantMedia\SimpleRepository\Commands;

use Illuminate\Console\GeneratorCommand;
use Illuminate\Support\Str;
use Symfony\Component\Console\Input\InputOption;

class RepositoryMakeCommand extends GeneratorCommand
{
	/**
	 * The console command name.
	 */
	protected $name = 'make:repository';

	/**
	 * The console command description.
	 */
	protected $description = 'Create a new repository class';

	/**
	 * The type of class being generated.
	 */
	protected $type = 'Repository';

	/**
	 * {@inheritdoc}
	 */
	protected function getStub(): string
	{
		return __DIR__ . DIRECTORY_SEPARATOR . 'stubs' . DIRECTORY_SEPARATOR . 'Repository.php.stub';
	}

	/**
	 * Get the default namespace for the class.
	 */
	protected function getDefaultNamespace($rootNamespace): string
	{
		$dir = $this->option('dir') ?? config('simple-repository.command.directory', 'Models');

		if ($this->option('group')) {
			return $rootNamespace . "\\{$dir}\\" . $this->getEntityPlural();
		}

		return $rootNamespace . "\\{$dir}";
	}

	/**
	 * Get the destination class path.
	 */
	protected function getPath($name): string
	{
		$dir = $this->option('dir') ?? config('simple-repository.command.directory', 'Models');
		$path = [$dir];

		if ($this->option('group')) {
			$path[] = $this->getEntityPlural();
		}

		$suffix = config('simple-repository.command.suffix', 'Repository');
		$path[] = $this->getEntityPlural() . $suffix . '.php';
		$path = app_path(implode(DIRECTORY_SEPARATOR, $path));

		return str_replace('\\', DIRECTORY_SEPARATOR, $path);
	}

	/**
	 * Replace the class name for the given stub.
	 */
	protected function replaceClass($stub, $name): string
	{
		$name = Str::pluralStudly($name);
		$suffix = config('simple-repository.command.suffix', 'Repository');

		if (stripos($name, 'repo') === false) {
			$name .= $suffix;
		}

		return parent::replaceClass($stub, $name);
	}

	/**
	 * Build the class with the given name.
	 *
	 * @throws \Illuminate\Contracts\Filesystem\FileNotFoundException
	 */
	protected function buildClass($name): string
	{
		$stub = $this->files->get($this->getStub());
		$stub = $this->replaceModelClass($stub);

		return $this->replaceNamespace($stub, $name)->replaceClass($stub, $name);
	}

	/**
	 * Replace the model class name placeholder.
	 */
	protected function replaceModelClass(string $stub): string
	{
		if ($this->option('model')) {
			$replace = $this->option('model');
		} else {
			$replace = Str::studly(Str::singular($this->getNameInput()));
		}

		return str_replace(['ModelClass'], $replace, $stub);
	}

	/**
	 * Get the entity plural name.
	 */
	protected function getEntityPlural(): string
	{
		return Str::pluralStudly($this->getNameInput());
	}

	/**
	 * Get the console command options.
	 *
	 * @return array<array<mixed>>
	 */
	protected function getOptions(): array
	{
		$defaultDir = config('simple-repository.command.directory', 'Models');

		return [
			['force', null, InputOption::VALUE_NONE, 'Create the class even if it already exists'],
			['group', null, InputOption::VALUE_NONE, 'Create the repository in an autogenerated folder'],
			['dir', null, InputOption::VALUE_REQUIRED, 'Directory to create the models.', $defaultDir],
			['model', null, InputOption::VALUE_OPTIONAL, 'Related model class'],
		];
	}
}
